import Head from 'next/head';
import Onboarding from '@/components/pages/onboarding';
import Test from '@/components/pages/test';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Onboarding />
        <Test />
      </main>
    </>
  );
}
